import type { Office } from "./search-types";

const OFFICE_IMAGES = [
  "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=600&h=400&fit=crop",
];

function getImages(offset: number = 0): string[] {
  const shuffled = [...OFFICE_IMAGES];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = (i + offset) % shuffled.length;
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, 3 + (offset % 3));
}

export const mockOffices: Office[] = [
  {
    id: "off-001",
    title: "Bureaux lumineux Haussmannien",
    address: "10 Rue du Faubourg Montmartre",
    district: "75009 Paris",
    lat: 48.8722,
    lng: 2.3411,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 11504,
    pricePerSqmYear: 580,
    surface: 238,
    seats: 22,
    floor: "3ème étage",
    availability: "immediate",
    leaseDuration: "3/6/9",
    offMarket: false,
    images: getImages(0),
    updatedAt: "2025-03-05",
  },
  {
    id: "off-002",
    title: "Open space moderne République",
    address: "25 Boulevard du Temple",
    district: "75003 Paris",
    lat: 48.8656,
    lng: 2.3627,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 18750,
    pricePerSqmYear: 625,
    surface: 360,
    seats: 40,
    floor: "5ème étage",
    availability: "immediate",
    leaseDuration: "3/6/9",
    offMarket: false,
    images: getImages(1),
    updatedAt: "2025-03-04",
  },
  {
    id: "off-003",
    title: "Coworking premium Champs-Élysées",
    address: "78 Avenue des Champs-Élysées",
    district: "75008 Paris",
    lat: 48.8717,
    lng: 2.3022,
    type: "coworking",
    leaseType: "coworking",
    transactionType: "location",
    priceMonthly: 4500,
    pricePerSqmYear: 900,
    surface: 60,
    seats: 10,
    floor: "6ème étage",
    availability: "immediate",
    leaseDuration: "Flexible",
    offMarket: false,
    images: getImages(2),
    updatedAt: "2025-03-05",
  },
  {
    id: "off-004",
    title: "Bureaux d'angle Opéra",
    address: "4 Rue de la Paix",
    district: "75002 Paris",
    lat: 48.8693,
    lng: 2.3312,
    type: "commercial",
    leaseType: "bail_precaire",
    transactionType: "location",
    priceMonthly: 8200,
    pricePerSqmYear: 720,
    surface: 136,
    seats: 14,
    floor: "2ème étage",
    availability: "after_agreement",
    leaseDuration: "23 mois",
    offMarket: true,
    images: getImages(3),
    updatedAt: "2025-03-03",
  },
  {
    id: "off-005",
    title: "Loft bureaux Bastille",
    address: "15 Rue de la Roquette",
    district: "75011 Paris",
    lat: 48.8533,
    lng: 2.3722,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 6800,
    pricePerSqmYear: 480,
    surface: 170,
    seats: 18,
    floor: "RDC",
    availability: "immediate",
    leaseDuration: "3/6/9",
    offMarket: false,
    images: getImages(4),
    updatedAt: "2025-03-02",
  },
  {
    id: "off-006",
    title: "Bureau privatif Sentier",
    address: "40 Rue d'Aboukir",
    district: "75002 Paris",
    lat: 48.8678,
    lng: 2.3478,
    type: "coworking",
    leaseType: "coworking",
    transactionType: "location",
    priceMonthly: 2800,
    pricePerSqmYear: 840,
    surface: 40,
    seats: 6,
    floor: "4ème étage",
    availability: "immediate",
    leaseDuration: "Mensuel",
    offMarket: false,
    images: getImages(0),
    updatedAt: "2025-03-05",
  },
  {
    id: "off-007",
    title: "Plateaux de bureaux Saint-Lazare",
    address: "112 Rue Saint-Lazare",
    district: "75008 Paris",
    lat: 48.8767,
    lng: 2.3256,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 25000,
    pricePerSqmYear: 600,
    surface: 500,
    seats: 55,
    floor: "2ème et 3ème étage",
    availability: "2025-06-01",
    leaseDuration: "6/9",
    offMarket: false,
    images: getImages(1),
    updatedAt: "2025-03-01",
  },
  {
    id: "off-008",
    title: "Salle de réunion Madeleine",
    address: "8 Boulevard de la Madeleine",
    district: "75001 Paris",
    lat: 48.8703,
    lng: 2.3250,
    type: "meeting_room",
    leaseType: "coworking",
    transactionType: "location",
    priceMonthly: 1200,
    pricePerSqmYear: 0,
    surface: 35,
    seats: 12,
    floor: "1er étage",
    availability: "immediate",
    leaseDuration: "À la journée",
    offMarket: false,
    images: getImages(2),
    updatedAt: "2025-03-04",
  },
  {
    id: "off-009",
    title: "Bureaux standing Trocadéro",
    address: "22 Avenue Kléber",
    district: "75016 Paris",
    lat: 48.8706,
    lng: 2.2933,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 32000,
    pricePerSqmYear: 850,
    surface: 450,
    seats: 50,
    floor: "4ème étage",
    availability: "after_agreement",
    leaseDuration: "3/6/9",
    offMarket: true,
    images: getImages(3),
    updatedAt: "2025-02-28",
  },
  {
    id: "off-010",
    title: "Sous-location Nation",
    address: "5 Place de la Nation",
    district: "75012 Paris",
    lat: 48.8487,
    lng: 2.3956,
    type: "commercial",
    leaseType: "sous_location",
    transactionType: "location",
    priceMonthly: 5400,
    pricePerSqmYear: 400,
    surface: 162,
    seats: 16,
    floor: "1er étage",
    availability: "immediate",
    leaseDuration: "12 mois",
    offMarket: false,
    images: getImages(4),
    updatedAt: "2025-03-03",
  },
  {
    id: "off-011",
    title: "Bureaux neufs Batignolles",
    address: "30 Rue Cardinet",
    district: "75017 Paris",
    lat: 48.8833,
    lng: 2.3161,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "location",
    priceMonthly: 14200,
    pricePerSqmYear: 520,
    surface: 328,
    seats: 35,
    floor: "RDC + 1er",
    availability: "immediate",
    leaseDuration: "3/6/9",
    offMarket: false,
    images: getImages(0),
    updatedAt: "2025-03-05",
  },
  {
    id: "off-012",
    title: "Coworking créatif Oberkampf",
    address: "60 Rue Oberkampf",
    district: "75011 Paris",
    lat: 48.8647,
    lng: 2.3767,
    type: "coworking",
    leaseType: "coworking",
    transactionType: "location",
    priceMonthly: 3200,
    pricePerSqmYear: 640,
    surface: 60,
    seats: 8,
    floor: "3ème étage",
    availability: "immediate",
    leaseDuration: "Mensuel",
    offMarket: false,
    images: getImages(1),
    updatedAt: "2025-03-04",
  },
  {
    id: "off-013",
    title: "Bureaux avec terrasse Montparnasse",
    address: "18 Rue de l'Arrivée",
    district: "75015 Paris",
    lat: 48.8422,
    lng: 2.3211,
    type: "commercial",
    leaseType: "bail_precaire",
    transactionType: "location",
    priceMonthly: 9800,
    pricePerSqmYear: 550,
    surface: 214,
    seats: 24,
    floor: "7ème étage",
    availability: "immediate",
    leaseDuration: "23 mois",
    offMarket: false,
    images: getImages(2),
    updatedAt: "2025-03-02",
  },
  {
    id: "off-014",
    title: "Bureaux vue Seine Bercy",
    address: "87 Quai de la Gare",
    district: "75013 Paris",
    lat: 48.8356,
    lng: 2.3756,
    type: "commercial",
    leaseType: "bail_commercial",
    transactionType: "vente",
    priceMonthly: 780000,
    pricePerSqmYear: 0,
    surface: 420,
    seats: 45,
    floor: "6ème étage",
    availability: "after_agreement",
    leaseDuration: "—",
    offMarket: true,
    images: getImages(3),
    updatedAt: "2025-02-27",
  },
  {
    id: "off-015",
    title: "Espace flex Le Marais",
    address: "12 Rue des Archives",
    district: "75004 Paris",
    lat: 48.8589,
    lng: 2.3544,
    type: "coworking",
    leaseType: "coworking",
    transactionType: "location",
    priceMonthly: 5600,
    pricePerSqmYear: 780,
    surface: 86,
    seats: 15,
    floor: "2ème étage",
    availability: "immediate",
    leaseDuration: "Flexible",
    offMarket: false,
    images: getImages(4),
    updatedAt: "2025-03-05",
  },
];
