import type { Client, Interaction, ActivityLog, Profile } from "@/types";

export const DEMO_MODE =
  !process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL === "your_supabase_url_here";

export const mockProfile: Profile = {
  id: "demo-user-001",
  full_name: "Franck Orsi",
  avatar_url: null,
  role: "admin",
  created_at: "2025-01-15T10:00:00Z",
  updated_at: "2025-03-01T10:00:00Z",
};

export const mockClients: Client[] = [
  {
    id: "client-001",
    name: "Marie Dupont",
    email: "marie.dupont@email.com",
    phone: "+33 6 12 34 56 78",
    company: "Tech Solutions SAS",
    address: "12 Rue de la Paix, 75002 Paris",
    notes: "Cliente fidèle depuis 2023. Intéressée par notre offre premium.",
    status: "active",
    created_by: "demo-user-001",
    created_at: "2025-01-20T09:00:00Z",
    updated_at: "2025-02-28T14:30:00Z",
  },
  {
    id: "client-002",
    name: "Jean Martin",
    email: "j.martin@startup.io",
    phone: "+33 6 98 76 54 32",
    company: "StartupIO",
    address: "45 Avenue des Champs-Élysées, 75008 Paris",
    notes: "Prospect chaud, relancer la semaine prochaine.",
    status: "lead",
    created_by: "demo-user-001",
    created_at: "2025-02-10T11:00:00Z",
    updated_at: "2025-03-01T09:00:00Z",
  },
  {
    id: "client-003",
    name: "Sophie Bernard",
    email: "sophie.b@design.fr",
    phone: "+33 7 11 22 33 44",
    company: "Design & Co",
    address: "8 Rue du Faubourg Saint-Honoré, 75008 Paris",
    notes: null,
    status: "active",
    created_by: "demo-user-001",
    created_at: "2025-01-05T08:00:00Z",
    updated_at: "2025-02-15T16:00:00Z",
  },
  {
    id: "client-004",
    name: "Pierre Leroy",
    email: "p.leroy@consulting.com",
    phone: "+33 6 55 44 33 22",
    company: "Leroy Consulting",
    address: "22 Boulevard Haussmann, 75009 Paris",
    notes: "Ancien client, contrat terminé en décembre.",
    status: "inactive",
    created_by: "demo-user-001",
    created_at: "2024-06-15T10:00:00Z",
    updated_at: "2024-12-31T17:00:00Z",
  },
  {
    id: "client-005",
    name: "Claire Moreau",
    email: "claire@moreau-events.fr",
    phone: "+33 6 77 88 99 00",
    company: "Moreau Events",
    address: "5 Place Vendôme, 75001 Paris",
    notes: "Organisatrice d'événements, potentiel partenariat.",
    status: "lead",
    created_by: "demo-user-001",
    created_at: "2025-02-25T14:00:00Z",
    updated_at: "2025-03-02T10:00:00Z",
  },
  {
    id: "client-006",
    name: "Thomas Petit",
    email: "thomas@petit-dev.com",
    phone: null,
    company: "Petit Dev",
    address: null,
    notes: "Développeur freelance, projet archivé.",
    status: "archived",
    created_by: "demo-user-001",
    created_at: "2024-03-10T09:00:00Z",
    updated_at: "2024-09-20T11:00:00Z",
  },
];

export const mockInteractions: (Interaction & { profiles?: { id: string; full_name: string }; clients?: { id: string; name: string } })[] = [
  {
    id: "inter-001",
    client_id: "client-001",
    user_id: "demo-user-001",
    type: "meeting",
    title: "Réunion de suivi trimestriel",
    description: "Revue des objectifs Q1. Marie est satisfaite du service. Discussion sur l'upgrade au plan premium.",
    occurred_at: "2025-03-01T10:00:00Z",
    created_at: "2025-03-01T10:30:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
    clients: { id: "client-001", name: "Marie Dupont" },
  },
  {
    id: "inter-002",
    client_id: "client-002",
    user_id: "demo-user-001",
    type: "call",
    title: "Appel de découverte",
    description: "Premier contact avec Jean. Intéressé par notre offre startup. Envoyer la brochure.",
    occurred_at: "2025-02-28T15:00:00Z",
    created_at: "2025-02-28T15:20:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
    clients: { id: "client-002", name: "Jean Martin" },
  },
  {
    id: "inter-003",
    client_id: "client-001",
    user_id: "demo-user-001",
    type: "email",
    title: "Envoi proposition commerciale",
    description: "Proposition pour le plan premium envoyée par email avec les conditions tarifaires.",
    occurred_at: "2025-02-25T09:00:00Z",
    created_at: "2025-02-25T09:05:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
    clients: { id: "client-001", name: "Marie Dupont" },
  },
  {
    id: "inter-004",
    client_id: "client-003",
    user_id: "demo-user-001",
    type: "note",
    title: "Note interne",
    description: "Sophie a mentionné un besoin en refonte de site web. À explorer.",
    occurred_at: "2025-02-20T11:00:00Z",
    created_at: "2025-02-20T11:00:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
    clients: { id: "client-003", name: "Sophie Bernard" },
  },
  {
    id: "inter-005",
    client_id: "client-005",
    user_id: "demo-user-001",
    type: "meeting",
    title: "Rendez-vous café",
    description: "Première rencontre avec Claire pour discuter d'un partenariat événementiel.",
    occurred_at: "2025-02-27T14:00:00Z",
    created_at: "2025-02-27T14:30:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
    clients: { id: "client-005", name: "Claire Moreau" },
  },
];

export const mockActivityLog: (ActivityLog & { profiles?: { id: string; full_name: string } })[] = [
  {
    id: "act-001",
    user_id: "demo-user-001",
    action: "client_created",
    entity_type: "client",
    entity_id: "client-005",
    metadata: { client_name: "Claire Moreau" },
    created_at: "2025-02-25T14:00:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "act-002",
    user_id: "demo-user-001",
    action: "interaction_created",
    entity_type: "interaction",
    entity_id: "inter-001",
    metadata: { type: "meeting", title: "Réunion de suivi trimestriel", client_id: "client-001" },
    created_at: "2025-03-01T10:30:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "act-003",
    user_id: "demo-user-001",
    action: "client_updated",
    entity_type: "client",
    entity_id: "client-001",
    metadata: { client_name: "Marie Dupont" },
    created_at: "2025-02-28T14:30:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "act-004",
    user_id: "demo-user-001",
    action: "interaction_created",
    entity_type: "interaction",
    entity_id: "inter-002",
    metadata: { type: "call", title: "Appel de découverte", client_id: "client-002" },
    created_at: "2025-02-28T15:20:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "act-005",
    user_id: "demo-user-001",
    action: "interaction_created",
    entity_type: "interaction",
    entity_id: "inter-005",
    metadata: { type: "meeting", title: "Rendez-vous café", client_id: "client-005" },
    created_at: "2025-02-27T14:30:00Z",
    profiles: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
];
