import type { Project, Document, Notification } from "@/types";

export const mockClientProfile = {
  id: "client-user-001",
  full_name: "Sophie Martin",
  avatar_url: null,
  role: "client" as const,
  created_at: "2025-01-10T10:00:00Z",
  updated_at: "2025-03-01T10:00:00Z",
};

export const mockProjects: (Project & { agent: { id: string; full_name: string; avatar_url: string | null } })[] = [
  {
    id: "proj-001",
    client_id: "client-user-001",
    agent_id: "demo-user-001",
    title: "Achat appartement T3 - Paris 11e",
    type: "purchase",
    current_stage: "financing",
    property_address: "45 Rue Oberkampf, 75011 Paris",
    property_price: 485000,
    description: "Appartement 3 pièces, 65m², 4ème étage avec ascenseur, balcon sud.",
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-03-01T14:00:00Z",
    agent: { id: "demo-user-001", full_name: "Franck Orsi", avatar_url: null },
  },
  {
    id: "proj-002",
    client_id: "client-user-001",
    agent_id: "demo-user-001",
    title: "Vente maison - Vincennes",
    type: "sale",
    current_stage: "offer",
    property_address: "12 Avenue du Château, 94300 Vincennes",
    property_price: 720000,
    description: "Maison 5 pièces, 120m², jardin 80m², garage.",
    created_at: "2025-02-01T11:00:00Z",
    updated_at: "2025-02-28T16:00:00Z",
    agent: { id: "demo-user-001", full_name: "Franck Orsi", avatar_url: null },
  },
];

export const mockDocuments: (Document & { uploader: { id: string; full_name: string } })[] = [
  {
    id: "doc-001",
    project_id: "proj-001",
    uploaded_by: "demo-user-001",
    name: "Compromis de vente - Oberkampf.pdf",
    type: "contract",
    file_url: "#",
    file_size: 2450000,
    status: "approved",
    created_at: "2025-02-20T10:00:00Z",
    uploader: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "doc-002",
    project_id: "proj-001",
    uploaded_by: "demo-user-001",
    name: "Diagnostic énergétique (DPE).pdf",
    type: "diagnostic",
    file_url: "#",
    file_size: 1200000,
    status: "approved",
    created_at: "2025-02-18T14:00:00Z",
    uploader: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "doc-003",
    project_id: "proj-001",
    uploaded_by: "client-user-001",
    name: "Justificatif de revenus 2024.pdf",
    type: "income",
    file_url: "#",
    file_size: 890000,
    status: "pending",
    created_at: "2025-03-01T09:00:00Z",
    uploader: { id: "client-user-001", full_name: "Sophie Martin" },
  },
  {
    id: "doc-004",
    project_id: "proj-001",
    uploaded_by: "demo-user-001",
    name: "Offre de prêt - Banque Populaire.pdf",
    type: "contract",
    file_url: "#",
    file_size: 3100000,
    status: "pending",
    created_at: "2025-03-02T11:00:00Z",
    uploader: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
  {
    id: "doc-005",
    project_id: "proj-002",
    uploaded_by: "client-user-001",
    name: "Titre de propriété - Vincennes.pdf",
    type: "property",
    file_url: "#",
    file_size: 1800000,
    status: "approved",
    created_at: "2025-02-05T10:00:00Z",
    uploader: { id: "client-user-001", full_name: "Sophie Martin" },
  },
  {
    id: "doc-006",
    project_id: "proj-002",
    uploaded_by: "demo-user-001",
    name: "Diagnostics obligatoires - Vincennes.pdf",
    type: "diagnostic",
    file_url: "#",
    file_size: 4500000,
    status: "approved",
    created_at: "2025-02-10T09:00:00Z",
    uploader: { id: "demo-user-001", full_name: "Franck Orsi" },
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    user_id: "client-user-001",
    type: "project_update",
    title: "Projet mis à jour",
    message: "Votre dossier de financement pour l'appartement Oberkampf a été transmis à la banque.",
    read: false,
    link: "/portal/projects/proj-001",
    created_at: "2025-03-02T14:00:00Z",
  },
  {
    id: "notif-002",
    user_id: "client-user-001",
    type: "document_request",
    title: "Document demandé",
    message: "Merci de déposer votre avis d'imposition 2024 pour compléter le dossier de financement.",
    read: false,
    link: "/portal/documents",
    created_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "notif-003",
    user_id: "client-user-001",
    type: "appointment",
    title: "Rendez-vous confirmé",
    message: "Visite du bien au 45 Rue Oberkampf confirmée le 5 mars à 14h.",
    read: true,
    link: "/portal/projects/proj-001",
    created_at: "2025-02-28T09:00:00Z",
  },
  {
    id: "notif-004",
    user_id: "client-user-001",
    type: "document_signed",
    title: "Compromis signé",
    message: "Le compromis de vente pour l'appartement Oberkampf a bien été signé par toutes les parties.",
    read: true,
    link: "/portal/documents",
    created_at: "2025-02-20T16:00:00Z",
  },
  {
    id: "notif-005",
    user_id: "client-user-001",
    type: "message",
    title: "Nouveau message de Franck Orsi",
    message: "Bonjour Sophie, j'ai reçu 2 offres pour votre maison à Vincennes. Je vous appelle demain pour en discuter.",
    read: true,
    link: null,
    created_at: "2025-02-27T17:30:00Z",
  },
];

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + " o";
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(0) + " Ko";
  return (bytes / (1024 * 1024)).toFixed(1) + " Mo";
}
